url: https://joshmcarthur.com
timezone: Pacific/Auckland
title: "Notes: Josh McArthur"
description: "I'm Josh McArthur, a web developer specializing in Ruby on Rails and Phoenix. I write posts about technology and hiking."
paginate: 10
kramdown:
  input: GFM
  hard_wrap: false
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
plugins:
  - jekyll-coffeescript
  - jekyll-gist
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-redirect-from
whitelist:
  - jekyll-coffeescript
  - jekyll-gist
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-redirect-from
