url: https://joshmcarthur.com
timezone: Pacific/Auckland
title: "Notes: Josh McArthur"
description: "I'm Josh McArthur, a web developer specializing in Ruby on Rails and Phoenix. I write posts about technology and hiking."
paginate: 10
paginate_path: posts/page/:num/
kramdown:
  input: GFM
  hard_wrap: false
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
collections:
  case_studies:
    output: true
    permalink: /case-studies/:title/
    sort_by: date
plugins:
  - jekyll-coffeescript
  - jekyll-gist
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-redirect-from
whitelist:
  - jekyll-coffeescript
  - jekyll-gist
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-redirect-from
